celery_progress_demo/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from download import urls as download_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    # Celery progress
	path('celery-progress/', include('celery_progress.urls')),

	# Demo app
	path('', include(download_urls))
]	

if settings.DEBUG:
	from django.conf.urls.static import static
	from django.contrib.staticfiles.urls import staticfiles_urlpatterns

	# Serve static and media files from development server
	urlpatterns += staticfiles_urlpatterns()
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

download/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 

from .views import delete_post, admin_panel, submit_tasks, posts, get_all_urls_with_tickbox, remove_all_selenium_tasks, remove_selenium_task, pass_json_data, start_task, delete_full_tasks_id, create_task_full, delete_tasks, insert_all_tasks_with_id, cancel_selenium_task, pause_selenium_task,resume_selenium_task, demo_view, selenium_skel_new_tasks, start_automation, sleepy, celery_check, selenium_test, pause_task
from . import views

app_name = 'download'

urlpatterns = [
	# Demo view
    path('admin_panel', admin_panel, name='admin_panel'),
    path(r'submit_tasks/<id>/', submit_tasks, name='submitted_values'),
    path('posts', posts, name='posts'),
	path(r'delete_post/<id>/', delete_post, name='delete_post'),
    path('demo', demo_view, name='demo'),
	path('automation', start_automation, name="automation"),
    path('testing', selenium_skel_new_tasks, name="testing"),
    path('sleepy', sleepy, name="sleepy"),
    path('check', celery_check, name="check"),
    path(r'pause/<id>/', pause_selenium_task, name='pause'),
    path(r'resume/<id>/', resume_selenium_task, name='resume'),
    path(r'cancel/<id>/', cancel_selenium_task, name='cancel'),
    path(r'remove/<id>/', remove_selenium_task, name='remove'),
    path(r'delete_all', remove_all_selenium_tasks, name='delete_all'),
	path('', views.index, name='index'),
    path(r'create', views.create, name='create'),
    path(r'edit/<id>/', views.edit, name='edit'),
    path(r'update/<id>/', views.update, name='update'),
    path(r'delete/<id>/', views.delete, name='delete'),
	path("upload", views.upload, name="upload"),
    # new tasks list for functions
    path(r'insert_all_tasks_with_id', insert_all_tasks_with_id, name='create_functions_task'),
    path(r'delete_tasks/<id>/', delete_tasks, name='delete_tasks'),
    # full tasks impementation
    # delete_full_tasks_id
    path(r'create_new_full_task', create_task_full, name='create_task_full'),
    path(r'delete_full_tasks_id/<id>/', delete_full_tasks_id, name='delete_tasks'),
    # final task start
    path(r'start_task', start_task, name='start_task'),
    path(r'get_all_urls_with_tickbox', get_all_urls_with_tickbox, name='get_all_urls_with_tickbox'),
    
    # path(r'^code_runner$', views.code_runner, name='code_runner'),
    path(r'pass_json_data', pass_json_data, name='pass_json_data'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

download/models.py
from django.db import models

# Create your models here.

class Member(models.Model):
    firstname = models.CharField(max_length=40)
    lastname = models.CharField(max_length=40)
    email = models.CharField(max_length=40)
    dob = models.CharField(max_length=40)
    phone_number = models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    ssn = models.CharField(max_length=40)
    city = models.CharField(max_length=40)
    state = models.CharField(max_length=40)
    password = models.CharField(max_length=40)
    


    def __str__(self):
        return self.firstname + " " + self.lastname + self.email + " " + self.dob + " " + self.phone_nuumber + " " + self.address + " " + self.ssn + " " + self.city + " " + self.state + " " + self.password


class Tasks_Celery(models.Model):
    task_id = models.CharField(max_length=40)
    description = models.CharField(max_length=40)
    progress = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    finished = models.CharField(max_length=40)
    


    def __str__(self):
        return self.task_id + " " + self.description + self.progress + " " + self.status + " " + self.finished



class Tasks_List(models.Model):
    task_id = models.CharField(max_length=40)
    description = models.CharField(max_length=40)
    extra_values = models.CharField(max_length=40)
    
    def __str__(self):
        return self.task_id + " " + self.description + " " + self.extra_values

class Full_Tasks_List(models.Model):
    task_id = models.CharField(max_length=40)
    full_task_id = models.CharField(max_length=40)
    user_inputs = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    
    def __str__(self):
        return self.task_id + " " + self.full_task_id + " " + self.user_inputs + " " + self.status


class Full_Tasks_ID(models.Model):
    task_id = models.CharField(max_length=40)
    # full_task_id = models.CharField(max_length=40)
    # user_inputs = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    
    def __str__(self):
        return self.task_id + " "  + self.status


class Posts(models.Model):
    # task_id = models.CharField(max_length=40)
    task_description = models.CharField(max_length=40)
    cost = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    
    def __str__(self):
        return self.task_description + " " + self.cost + " " + self.status



class Users(models.Model):
    user_id = models.CharField(max_length=40)
    outputs = models.CharField(max_length=40)
    # user_inputs = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    
    def __str__(self):
        return self.user_id + " " + self.outputs +  +  self.status



class All_Tasks(models.Model):
    task_id = models.CharField(max_length=40)
    task_description = models.CharField(max_length=40)
    user_id = models.CharField(max_length=40)
    status = models.CharField(max_length=40)
    costs = models.CharField(max_length=40)
    submitted_values = models.CharField(max_length=40)
    
    def __str__(self):
        return self.task_id + " " + self.task_description + " " + self.user_id + " " + self.status + " " + self.costs




from django.contrib.auth.models import User
# from django.db import models
from django.utils import timezone


class Owner(User):
    """Inherited Model definition for Owners"""

    orderList = models.TextField(default="")

download/forms.py
from django import forms
from .models import Member, Tasks_Celery, Tasks_List, Full_Tasks_List, Full_Tasks_ID


class DownloadForm(forms.Form):
    url = forms.CharField(max_length=255, widget=forms.TextInput({
        'class': 'form-control',
        'placeholder': 'Enter URL to download...',
    }))


members = Tasks_List.objects.all()
# last_task_id = Full_Tasks_ID.objects.all().order_by("-task_id")[0]
# context = {'members': members}
# tasks -list in the form as task_id desc

INTEGER_CHOICES= [tuple([x,x]) for x in range(1,32)]
# INTEGER_CHOICES = [tuple([x.task_id, x.description]) for x in members]


class UserForm(forms.Form):
    # last_name= forms.CharField(max_length=100)
    # email= forms.EmailField()
    # age= forms.IntegerField()
    task_id = forms.IntegerField(
        label="Task Func:", widget=forms.Select(choices=INTEGER_CHOICES))
    # user_input = forms.CharField(max_length=100)
    user_inputs = forms.CharField(max_length=100)
    # task_name = forms.CharField(max_length=100)
    full_task_id = forms.CharField(max_length=100)

download/views.py
from celery_progress.backend import Progress
from django.shortcuts import render, redirect
from .models import All_Tasks, Owner, Member, Posts, Tasks_Celery, Tasks_List, Full_Tasks_List, Full_Tasks_ID, Users
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from .forms import DownloadForm, UserForm
from celery.app.task import Task
import time
from .tasks import main_task, ProcessDownload, automation_with_selenium, go_to_sleep, testing_selenium


def demo_view(request):
    # If method is POST, process form data and start task
    if request.method == 'POST':
        # Get form instance
        form = DownloadForm(request.POST)

        # form = UserForm(request.POST)

        if form.is_valid():
            # Retrieve URL from form data
            url = form.cleaned_data['url']

            print(f'Downloading: {url}')
            # Create Task
            download_task = ProcessDownload.delay(url)
            # Get ID
            task_id = download_task.task_id
            # Print Task ID
            print(f'Celery Task ID: {task_id}')

            # Return demo view with Task ID
            return render(request, 'progress.html', {'form': form, 'task_id': task_id})
        else:
            # Return demo view
            return render(request, 'progress.html', {'form': form})
    else:
        # Get form instance
        form = DownloadForm()
        # Return demo view
        return render(request, 'progress.html', {'form': form})


def start_automation(request):
    if request.method == 'POST':
        # Get form instance
        form = DownloadForm(request.POST)

        if form.is_valid():
            # Retrieve URL from form data
            url = form.cleaned_data['url']

            print(f'Downloading: {url}')
            # Create Task
            download_task = automation_with_selenium.delay()
            # Get ID
            task_id = download_task.task_id
            # Print Task ID
            print(f'Celery Task ID: {task_id}')

            # Return demo view with Task ID
            return render(request, 'progress.html', {'form': form, 'task_id': task_id})
        else:
            # Return demo view
            return render(request, 'progress.html', {'form': form})
    else:
        # Get form instance
        form = DownloadForm()
        # Return demo view
        return render(request, 'progress.html', {'form': form})


def selenium_test(request):
    task = testing_selenium.delay("https://google.com")
    # form = DownloadForm(request.POST)
    task_id = task.task_id
    return render(request, 'progress.html', {'task_id': task_id})


def sleepy(request):
    task = go_to_sleep.delay(1)
    # print(task.task_id)
    tasks_db = Tasks_Celery(
        task_id=task.task_id, description="sleepy", progress="0", finished="False")
    tasks_db.save()
    return render(request, 'download/sleepy.html', {'task_id': task.task_id})


def index(request):
    members = Member.objects.all()
    context = {'members': members}
    return render(request, 'download/index.html', context)


def celery_check(request):
    members = Tasks_Celery.objects.all()
    context = {'members': members}
    # for member in members:
    # members.sort(reverse=True)
    members = members.order_by('-id')
    celery_task_ids = {member.id: member.task_id for member in members}
    print(celery_task_ids)
    # sorted([(value,key) for (key,value) in celery_task_ids.items()])
    # a = sorted([(value,key) for (key,value) in celery_task_ids.items()])
    # print(a)
    # celery_task_ids.reverse()
    return render(request, 'download/celery_check.html', context={'celery_task_ids': celery_task_ids})


def create(request):
    member = Member(firstname=request.POST['firstname'], lastname=request.POST['lastname'], email=request.POST['email'], dob=request.POST['dob'], phone_number=request.POST['phone_number'],
                    address=request.POST['address'], ssn=request.POST['ssn'], city=request.POST['city'], state=request.POST['state'], password=request.POST['password'])
    member.save()
    return redirect('/')


def edit(request, id):
    members = Member.objects.get(id=id)
    context = {'members': members}
    return render(request, 'download/edit.html', context)


def update(request, id):
    member = Member.objects.get(id=id)
    member.firstname = request.POST['firstname']
    member.lastname = request.POST['lastname']
    member.email = request.POST['email']
    member.dob = request.POST['dob']
    member.phone_number = request.POST['phone_number']
    member.address = request.POST['address']
    member.ssn = request.POST['ssn']
    member.lastname = request.POST['lastname']
    member.password = request.POST['password']
    member.city = request.POST['city']
    member.state = request.POST['state']
    member.save()
    return redirect('/')


def delete(request, id):
    member = Member.objects.get(id=id)
    member.delete()
    return redirect('/')


def upload(request):
    if request.method == 'POST' and request.FILES['upload']:
        upload = request.FILES['upload']
        fss = FileSystemStorage()
        file = fss.save(upload.name, upload)
        file_url = fss.url(file)

        print(str(file_url))

        return render(request, 'download/upload.html', {'file_url': file_url})
    return render(request, 'download/upload.html')


def pause_task(request, id):
    Task.update_state(self=go_to_sleep, task_id=id, state='CANCEL')
    return redirect('/check')


def resume_task(request, tid):
    Task.update_state(self=long_task, task_id=tid, state='RESUME')
    return 'Your task will be resumed !'


def cancel_task(request, tid):
    Task.update_state(self=long_task, task_id=tid, state='CANCEL')
    return 'Your task will be cancelled !'


def selenium_skel_new_tasks(request):
    # task = testing_selenium.delay("https://google.com")
    tasks_db = Tasks_Celery(task_id="Not Assigned", description="start New Automation",
                            progress="0", status="start", finished="False",)

    tasks_db.save()
    print(tasks_db.id)
    task = testing_selenium.delay(melo=tasks_db.id, url="https://google.com")
    # form = DownloadForm(request.POST)
    task_id = task.task_id
    return render(request, 'download/selenium_progress.html', {'task_id': task_id})


def pause_selenium_task(request, id):
    member = Tasks_Celery.objects.get(task_id=id)
    print(member)
    # tasks_db = Tasks_Celery(task_id=task.task_id, description="sleepy", progress="0", finished="False")
    # tasks_db.save()
    member.status = "pause"
    member.save()
    print(member)
    return redirect("/check")


def resume_selenium_task(request, id):
    member = Tasks_Celery.objects.get(task_id=id)
    print(member)
    # tasks_db = Tasks_Celery(task_id=task.task_id, description="sleepy", progress="0", finished="False")
    # tasks_db.save()
    member.status = "resume"
    member.save()
    print(member)
    return redirect("/check")


def cancel_selenium_task(request, id):
    member = Tasks_Celery.objects.get(task_id=id)
    print(member)
    # tasks_db = Tasks_Celery(task_id=task.task_id, description="sleepy", progress="0", finished="False")
    # tasks_db.save()
    member.status = "cancel"
    member.save()
    print(member)
    return redirect("/check")

#####################################  functions with tasks  ###############################################


def get_all_tasks_from_db(request):
    members = Tasks_List.objects.all()
    context = {'members': members}
    return render(request, 'download/new_task.html', context)


def insert_all_tasks_with_id(request):
    if(request.method == "POST"):
        member = Tasks_List(
            task_id=request.POST['task_id'], description=request.POST['description'], extra_values=request.POST['extra_values'])
        member.save()
    members = Tasks_List.objects.all()
    context = {'members': members}
    return render(request, 'download/add_tasks_into_db.html', context)


def delete_tasks(request, id):
    member = Tasks_List.objects.get(id=id)
    member.delete()
    members = Tasks_List.objects.all()
    context = {'members': members}
    return redirect("/insert_all_tasks_with_id")

##################### creating full task from Task_List ##########


def create_task_full(request):
    # create a db to add task with task_id
    # add same task id next task
    # get all tasks list from db
    id_needed = "0"
    # member = Full_Tasks_ID(task_id="1", status="pending")
    # member.save()
    # last_task_id = Full_Tasks_ID.objects.all()
    # print(last_task_id)
    # if(last_task_id is None):
    #     member = Full_Tasks_ID(task_id="1", status="pending")
    #     member.save()
    #     print("last_task_id: " + last_task_id)
    # else:
    last_task_id = Full_Tasks_ID.objects.all()
    for task_id in last_task_id:
        id_needed = task_id.task_id
    print(id_needed)
    if(id_needed == "0"):
        member = Full_Tasks_ID(task_id="1", status="pending")
        member.save()
        last_task_id = Full_Tasks_ID.objects.all()
        for task_id in last_task_id:
            id_needed = task_id.task_id
            print((id_needed))
        # print("last_task_id: " + last_task_id)
    form = UserForm(initial={'full_task_id': id_needed})

    if request.method == 'POST':
        # Get form instance
        form = UserForm(request.POST)

        # form = UserForm(request.POST)

        if form.is_valid():
            # Retrieve URL from form data
            # status = form.cleaned_data['task_func']
            user_inputs = form.cleaned_data['user_inputs']
            full_task_id = form.cleaned_data['full_task_id']

download/templates/download/add_tasks_into_db.html
{% extends 'download/base.html' %}

{% block body %}
<form class="form-inline"  action='insert_all_tasks_with_id' method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="task_id">Task ID</label>
        <input type="text" name="task_id" class="form-control" style="width:30%;" required="required"/>
        <label for="description">Description</label>
        <input type="text" name="description" class="form-control" style="width:30%;" required="required"/>
        <label for="extra_values">Extra Values</label>
        <input type="text" name="extra_values" class="form-control" style="width:30%;" required="required"/>
        <button type="submit" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-plus"></span> ADD</button>
    </div>
</form>


<table class="table table-bordered">
    <thead class="alert-info">
        <tr>
            <th>#</th>
            <th>Task ID</th>
            <th>Description</th>
            <th>Extra Values</th>
            
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{ member.id }}
                <form action="code_runner" method="POST">
                    {% csrf_token %}
                    <input type="text" name="id" class="form-control" style="width:30%;display: none" value='{{ member.id }}' />
                    <button type="submit">Call</button>
                </form>
            </td>
            <td>{{ member.task_id }}</td>
            <td>{{ member.description }}</td>
            <td>{{ member.extra_values }}</td>
            
            <td><center><a class="btn btn-sm btn-warning" href="delete_tasks/{{ member.task_id }}"><span class="glyphicon glyphicon-edit"></span> Update</a> <a class="btn btn-sm btn-danger" href="delete_tasks/{{ member.id }}"><span class="glyphicon glyphicon-trash"></span> Remove</a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

download/templates/download/admin_panel.html
{% extends 'download/base.html' %}



{% block body %}


<form class="form-inline"  action="admin_panel" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="task_description">task_description</label>
        <input type="text" name="task_description" class="form-control" style="width:30%;" required="required"/>
        <label for="cost">cost</label>
        <input type="text" name="cost" class="form-control" style="width:30%;" required="required"/>
        <label for="status">status</label>
        <input type="text" name="status" class="form-control" style="width:30%;" required="required"/>
        <button type="submit" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-plus"></span> ADD</button>
    </div>
</form>
<br />
<h2>Tasks List</h2>
<table class="table table-bordered">
    <thead class="alert-info">
        <tr>
            <th>#</th>
            <!-- <th>task_id</th> -->
            <th>task_description</th>
            <th>cost</th>
            <th>status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{ member.id }}
                <form action="code_runner" method="POST">
                    {% csrf_token %}
                    <input type="text" name="id" class="form-control" style="width:30%;display: none" value='{{ member.id }}' />
                    <button type="submit">Call</button>
                </form>
            </td>
            <!-- <td>{{ member.task_id }}</td> -->
            <td>{{ member.task_description }}</td>
            <td>{{ member.cost }}</td>
            <td>{{ member.status }}</td>
            <td><center><a class="btn btn-sm btn-danger" href="delete_post/{{ member.id }}"><span class="glyphicon glyphicon-trash"></span> Remove</a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>Users List</h2>
<table class="table table-bordered">
    <thead class="alert-info">
        <tr>
            <th>#</th>
            <th>user_id</th>
            <th>status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for member in users %}
        <tr>
            <td>{{ member.id }}
                <form action="code_runner" method="POST">
                    {% csrf_token %}
                    <input type="text" name="id" class="form-control" style="width:30%;display: none" value='{{ member.id }}' />
                    <button type="submit">Call</button>
                </form>
            </td>
            <td>{{ member.user_id }}</td>
            <!-- <td>{{ member.outputs }}</td> -->
            <td>{{ member.status }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="submit_tasks/{{ member.id }}"><span class="glyphicon glyphicon-edit"></span> Update</a> <a class="btn btn-sm btn-danger" href="delete/{{ member.id }}"><span class="glyphicon glyphicon-trash"></span> Remove</a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<h2>All tasks list</h2>
<table class="table table-bordered">
    <thead class="alert-info">
        <tr>
            <th>#</th>
            <th>task_id</th>
            <th>user_id</th>
            <th>task_description</th>
            <th>status</th>
            <th>costs</th>
            <th>submitted_values</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for member in tasks_progress %}
        <tr>
            <td>{{ member.id }}
                <form action="code_runner" method="POST">
                    {% csrf_token %}
                    <input type="text" name="id" class="form-control" style="width:30%;display: none" value='{{ member.id }}' />
                    <button type="submit">Call</button>
                </form>
            </td>
            <td>{{ member.task_id }}</td>
            <td>{{ member.user_id }}</td>
            <td>{{ member.task_description }}</td>
            <td>{{ member.status }}</td>
            <td>{{ member.costs }}</td>
            <td>{{ member.submitted_values }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="submit_tasks/{{ member.id }}"><span class="glyphicon glyphicon-edit"></span> Update</a> <a class="btn btn-sm btn-danger" href="delete/{{ member.id }}"><span class="glyphicon glyphicon-trash"></span> Remove</a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

download/templates/download/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'download/css/bootstrap.css' %}"/>
    </head>
<body>
    <nav class="navbar navbar-default" style="background-color: #28a4c9;text-align: center;">
        <div class="container-fluid">
            <a class="navbar-brand" style="text-align: center;" href="https://itsourcecode.com">Melo's Task</a>
        </div>
    </nav>
    <div class="col-md-3"></div>
    <div class="col-md-6 well">
        <h3 class="text-primary">Task Manager : Earn From Tasks</h3>
        <hr style="border-top:1px dotted #000;"/>
        {% block body %}
        {% endblock %}
    </div>

</body>
</html>


download/templates/download/code_runner.html
{% extends 'crud/base.html' %}
{% block body %}
<form action="{% url 'code_runner' %}" method="POST">
    {% csrf_token %}
    <button type="submit">{{ members.firstname }}</button>
</form>
{% endblock %}

download/templates/download/create_new_full_task.html
{% extends 'download/base.html' %}


{% block body %}
<!-- all ids with scrollable select -->
<!-- open a box for inputs -->
<!--  a button with post request -->

<h1> Select predefined tasks: </h1>
    <!-- <form action="action_form.php" method="get">
      <input type="text" list="airports" name="airports"> 
      <datalist id="airports">
    {% for task in tasks %}
        <option value="{{task.task_id}}"
            {% if task == task.task_id %}selected="selected"{% endif %}>
            {{task.description}}
            </option>
         {% endfor %}
        
      </datalist>
      <label for="extra_values">Extra Values</label>
        <input type="text" name="extra_values" class="form-control" style="width:30%;"/>
      <input type="submit" value="confirm">
    </form> -->

    <div class="container" style="padding-top: 20px;">
        <form action="{% url 'download:create_task_full' %}" method="post" style="display: inline;" id="melodic">
            {% csrf_token %}
            <div class="form-group">
                <div class="input-group mb-3" align="center" style="margin:0 auto;">
                  {{ form }}
                  <div class="input-group-append">
                    <div id="dynamicInput[0]">
                        Entry 1<br><input type="text" name="myInputs[]"> 
                        <input type="button" value="+" onClick="addInput();">
                    </div>
                    <button class="btn btn-primary" type="submit" style="width:120px;">
                        <strong>Add Task</strong>
                    </button>
                  </div>
                </div>
            </div>
            {{ form.errors }}
        </form>
    </div>



<table class="table table-bordered">
    <thead class="alert-info">
        <tr>
            <th>#</th>
            <th>Task ID</th>
            <th>Full Task ID</th>
            <th>User Inputs</th>
            <th>Status</th>
            
        </tr>
    </thead>
    <tbody>
        {% for member in full_tasks %}
        <tr>
            <td>{{ member.id }}
                <form action="code_runner" method="POST">
                    {% csrf_token %}
                    <input type="text" name="id" class="form-control" style="width:30%;display: none" value='{{ member.id }}' />
                    <button type="submit">Call</button>
                </form>
            </td>
            <td>{{ member.task_id }}</td>
            <td>{{ member.full_task_id }}</td>
            <td>{{ member.user_inputs }}</td>
            <td>{{ member.status }}</td>
            
            <td><center><a class="btn btn-sm btn-warning" href="delete_tasks/{{ member.id }}"><span class="glyphicon glyphicon-edit"></span> Update</a> <a class="btn btn-sm btn-danger" href="delete_full_tasks_id/{{ member.id }}"><span class="glyphicon glyphicon-trash"></span> Remove</a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    var counter = 1;
    var dynamicInput = [];
    
    function addInput(){
        var newdiv = document.createElement('div');
        newdiv.id = dynamicInput[counter];
        newdiv.innerHTML = "Entry " + (counter + 1) + " <br><input type='text' name='myInputnames[]' placeholder='input_name'>  <input type='text' name='myInputvalues[]' placeholder='input_values'> <input type='button' value='-' onClick='removeInput("+dynamicInput[counter]+");'>";
        document.getElementById('melodic').appendChild(newdiv);
        counter++;
    }
      
      function removeInput(id){
        var elem = document.getElementById(id);
        return elem.parentNode.removeChild(elem);
      }
    </script>

{% endblock %}

download/templates/download/posts.html
{% extends 'download/base.html' %}



{% block body %}


<!-- <form class="form-inline"  action="posts" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="task_description">task_description</label>
        <input type="text" name="task_description" class="form-control" style="width:30%;" required="required"/>
        <label for="cost">cost</label>
        <input type="text" name="cost" class="form-control" style="width:30%;" required="required"/>
        <label for="status">status</label>
        <input type="text" name="status" class="form-control" style="width:30%;" required="required"/>
        <button type="submit" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-plus"></span> ADD</button>
    </div>
</form> -->
<br />
<table class="table table-bordered">
    <thead class="alert-info">
        <tr>
            <th>#</th>
            <!-- <th>task_id</th> -->
            <th>task_description</th>
            <th>cost</th>
            <th>status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{ member.id }}
                <form action="code_runner" method="POST">
                    {% csrf_token %}
                    <input type="text" name="id" class="form-control" style="width:30%;display: none" value='{{ member.id }}' />
                    <button type="submit">Call</button>
                </form>
            </td>
            <!-- <td>{{ member.task_id }}</td> -->
            <td>{{ member.task_description }}</td>
            <td>{{ member.cost }}</td>
            <td>{{ member.status }}</td>
            <td><center><a class="btn btn-sm btn-warning" href="submit_tasks/{{ member.id }}"><span class="glyphicon glyphicon-edit"></span> Update</a> <a class="btn btn-sm btn-danger" href="delete/{{ member.id }}"><span class="glyphicon glyphicon-trash"></span> Remove</a></center></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}